input {
  beats {
    port => 5044
  }
}

filter {
  json {
    source => "message"
  }

  mutate {
    remove_field => ["@version", "ecs", "input", "agent", "container"]
  }
}

# Elasticsearch local
output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "logs"
  }

  # Oodle
  http {
    url => "https://${OODLE_INSTANCE}-logs.collector.oodle.ai/ingest/v1/logs"
    http_method => "post"
    format => "json_batch"
    content_type => "application/json"
    headers => {
      "X-OODLE-INSTANCE" => "${OODLE_INSTANCE}"
      "X-API-KEY" => "${OODLE_API_KEY}"
    }
  }
}
