filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            contains:
              docker.container.name: demo-app
          config:
            - type: docker
              containers.ids:
                - "${data.docker.container.id}"

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info

http.enabled: true
http.host: "0.0.0.0"
http.port: 5066
