################################################################################
# Datadog AWS Integration (account-level — apply ONCE per AWS account)
#
# Mirrors the official setup guide:
# https://docs.datadoghq.com/integrations/guide/aws-terraform-setup/?tab=awscommercialcloud&site=us5
#
# Creates an IAM role Datadog can assume to pull CloudWatch metrics, resource
# metadata, and (here) ECS data, then registers it with Datadog.
################################################################################

provider "aws" {
  region = var.aws_region
}

# The Datadog provider reads DD_API_KEY and DD_APP_KEY from the environment.
provider "datadog" {
  api_url = var.dd_api_url
}

# Datadog-maintained list of the exact IAM permissions the integration needs.
data "datadog_integration_aws_iam_permissions" "datadog" {}

# Trust policy: allow Datadog's AWS account to assume this role, scoped to the
# external ID generated by the integration resource below.
data "aws_iam_policy_document" "assume_role" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "AWS"
      identifiers = [var.datadog_aws_account_principal]
    }
    condition {
      test     = "StringEquals"
      variable = "sts:ExternalId"
      values   = [datadog_integration_aws_account.main.auth_config.aws_auth_config_role.external_id]
    }
  }
}

# The permission list exceeds the 6144-char IAM policy limit, so split it into
# size-bounded chunks and attach one managed policy per chunk.
locals {
  all_permissions   = data.datadog_integration_aws_iam_permissions.datadog.iam_permissions
  target_chunk_size = 5900

  permission_sizes = [for perm in local.all_permissions : length(perm) + 3]
  cumulative_sizes = [
    for i in range(length(local.permission_sizes)) :
    sum(slice(local.permission_sizes, 0, i + 1))
  ]
  chunk_assignments = [for size in local.cumulative_sizes : floor(size / local.target_chunk_size)]
  chunk_numbers     = distinct(local.chunk_assignments)
  permission_chunks = [
    for chunk_num in local.chunk_numbers : [
      for i, perm in local.all_permissions : perm if local.chunk_assignments[i] == chunk_num
    ]
  ]
}

data "aws_iam_policy_document" "datadog" {
  count = length(local.permission_chunks)

  statement {
    actions   = local.permission_chunks[count.index]
    resources = ["*"]
  }
}

resource "aws_iam_policy" "datadog" {
  count = length(local.permission_chunks)

  name   = "DatadogAWSIntegrationPolicy-${count.index + 1}"
  policy = data.aws_iam_policy_document.datadog[count.index].json
}

resource "aws_iam_role" "datadog" {
  name               = "DatadogIntegrationRole"
  description        = "Role for the Datadog AWS integration"
  assume_role_policy = data.aws_iam_policy_document.assume_role.json
}

resource "aws_iam_role_policy_attachment" "datadog" {
  count = length(local.permission_chunks)

  role       = aws_iam_role.datadog.name
  policy_arn = aws_iam_policy.datadog[count.index].arn
}

resource "aws_iam_role_policy_attachment" "security_audit" {
  role       = aws_iam_role.datadog.name
  policy_arn = "arn:aws:iam::aws:policy/SecurityAudit"
}

resource "datadog_integration_aws_account" "main" {
  aws_account_id = var.aws_account_id
  aws_partition  = "aws"

  aws_regions {
    include_all = true
  }

  auth_config {
    aws_auth_config_role {
      role_name = "DatadogIntegrationRole"
    }
  }

  resources_config {
    cloud_security_posture_management_collection = false
    extended_collection                          = true
  }

  traces_config {
    xray_services {}
  }

  logs_config {
    lambda_forwarder {}
  }

  metrics_config {
    namespace_filters {}
  }
}
